site_name: 'HASP - Open Hardware edition'
site_description: 'Littlev Graphics Library on the MCU to drive a cheap commodity display'
site_author: 'Francis Van Roie'

repo_url: https://github.com/fvanroie/hasp-docs

theme: 
  name: windmill

strict: true

nav:
  - Home: index.md
  - hardware.md
  - Installation:
    - ESP32 Installation: ESP32.md
    - ESP8266 Installation: ESP8266.md
    - Wi-Fi Setup: wifi-setup.md
  - commands.md
  - Design:
    - pages.md
    - objects.md
    - styling.md
    - fonts.md
  - example-pages.md
  - FAQ: faq.md
  - firmware-update.md
  - Displays:
    - displays/MHS4001.md
    - displays/MRB3511.md
    - displays/Waveshare_40RPi_LCD(C).md
  - compiling.md
  - license.md

markdown_extensions:
  - toc:
     permalink: "~"
     toc_depth: 3
  - admonition
  - pymdownx.emoji
  - attr_list

extra:
  history_buttons: false
  version: v0.31
