site_name: 'HASP - Open SwitchPlate'
site_description: 'Open firmware for MCUs to drive a cheap commodity touch display'
site_author: 'Francis Van Roie'

repo_url: https://github.com/fvanroie/hasp-lvgl
edit_uri: https://github.com/fvanroie/hasp-docs/edit/master/docs/

theme: 
  name: windmill
  custom_dir: custom_theme

strict: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation:
    - ESP32 Installation: ESP32.md
    - ESP8266 Installation: ESP8266.md
    - Wi-Fi Setup: wifi-setup.md
  - Configuration:
    - configuration/http.md
    - configuration/wifi.md
    - configuration/mqtt.md
    - configuration/hasp.md
    - configuration/display.md
    - configuration/gpio.md
    - configuration/debug.md
  - Design:
    - pages.md
    - objects.md
    - fonts.md
    - styling.md
  - Example Pages:
    - Jaffa Sunrise: example-1.md
    - Dash UI: example-2.md
    - Widgets Demo: example-0.md
  - commands.md
  - FAQ: faq.md
  - firmware-update.md
  - Displays:
    - displays/ILI9341_IPS.md
    - displays/MHS4001.md
    - displays/MRB3511.md
    - displays/Waveshare_RPi_LCD_Rev_C.md
  - compiling.md
  - license.md

markdown_extensions:
  - toc:
     permalink: "~"
     toc_depth: 3
  - admonition
  - pymdownx.emoji
  - attr_list

extra:
  history_buttons: false
  version: v0.3.1

plugins:
  - search
  - table-reader
